name: Robert Meares
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74123
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b4bbc1'
    - '#ba9863'
    - '#7c8582'
    - '#65625b'
    - '#181d17'
  brandStrength: 0
  lightness: 0.875
  saturation: 1
  rhythmicContrast: 0
purpose: []
