name: Robert Meares
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.7293907
  brandStrength: 0.7168459
  lightness: 0.5842294
  brandColors:
    - '#A5D9F1'
    - '#1C1E2B'
    - '#895F49'
    - '#AF9DB3'
    - '#E4E474'
  rhythmicContrast: 0
typography_spectrum: 0.811828
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.1666667
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
